import Head from "next/head";

import SearchBar from "../components/SearchBar";
import NewsList from "../components/NewsList";

import { useState } from "react";

export default function Home() {
  const [searchTerm, setSearchTerm] = useState("");
  return (
    <>
      <Head>
        <title>React Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white h-full pt-6 flex flex-col items-center justify-start">
        <SearchBar searchTerm={searchTerm} setSearchTerm={setSearchTerm} />
        <NewsList searchTerm={searchTerm} />
      </main>
    </>
  );
}
